### ISSUE TITLE
Type in sendGreeting?

### ISSUE THREAD

**Issue by MatthewBregg** [JohnReedLOL/Nineteen_Characters#101]
MapEntity_Relation
Typo for sendGreeting [initiate chat] in down_left direction

**Comment by JohnReedLOL** [comment]
Huh? Which entity? Which tile?

**Comment by MatthewBregg** [comment]
Not sure, copied this from the google doc.

**Comment by MatthewBregg** [comment]
CLOSED, UNABLETOREPRODUCE
