### ISSUE TITLE
Minicontroller conflates similar commands

### ISSUE THREAD

**Issue by amstewart** [JohnReedLOL/Nineteen_Characters#113]
Concerns: CommandMiniController.java

Due to the way that processCommand() parses the input "foo", commands which begin similarly will be conflated. For example, command:save and command:save-controls both begin with the substring "save". Therefore, processCommand() will run and return whichever process is declared in the method body first. In this case, command:save is declared first, so both /save and /save-controls will run processSave().

**Comment by MatthewBregg** [comment]
Ah... Hmm, well, can just check for save-command first?

**Comment by amstewart** [comment]
I can do that as a quick-fix, but it shouldn't be a permanent solution.

**Comment by MatthewBregg** [comment]
Oh, I just did it myselfas a quick fix.

**Comment by MatthewBregg** [comment]
Well, I guess the other option is to extract the command portion of the string, and to use that. I can do that right now pretty easily.

**Comment by amstewart** [comment]
It'd be pretty cool...

**Comment by MatthewBregg** [comment]
Done.
It's much neater now, don't know what I was thinking when I wrote it the first time.
