### ISSUE TITLE
Talking is broken / correct reply strings are not sent.

### ISSUE THREAD

**Issue by JohnReedLOL** [JohnReedLOL/Nineteen_Characters#114]
Matt! How is it that every time we change something in one part of your code, something else in your code breaks?

**Comment by MatthewBregg** [comment]
I was telling you when writing it that the code for talking was crazy. 
I really don't like how it turned out with that.

**Comment by MatthewBregg** [comment]
Ok, someone when refactoring controller forget to pass the talking string in.
Fixed.
